//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juego.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("juego.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the air was filled with thick fog slowly replaced with dark smothering smog from the city
        ///as the flying ship neared the dock, gears shifted rotating the thrusters and slowing the pace, the sound of a bustiling city replaced the wails of the waves
        ///my box was placed in the dock, as two thugs cames and carried me to a wagon. driving slowly through a dark alley.
        ///even thrugh my cage, i was choking on the air  of this disgusting city, with the ground covered in soot and sky chocked in smoke..
        /// </summary>
        public static string scenes_1_text {
            get {
                return ResourceManager.GetString("scenes_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es el año 2058, Tuviste una noche pesada como detective privado en Liverpool, Inglaterra.
        ///En eso tocan a tu puerta. 
        ///Al parecer alguien asesino a tu hermana en Londres esa misma noche. 
        ///Y aquí es donde empieza el juego.
        ///#
        ///Llegas al cuarto donde fue asesinada, es un cuarto chico, alfombra morada
        ///una mesita y la cama. Al fondo esta la puerta para ir al baño. Llega el jefe de policia.
        ///que decides hacer:............
        ///#
        ///1) irme de la habitacion
        ///#
        ///2) quedarme a platicar con el don
        ///
        ///
        ///.
        /// </summary>
        public static string scenes_2_file {
            get {
                return ResourceManager.GetString("scenes_2_file", resourceCulture);
            }
        }
    }
}
